// Next.js and React related
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

// Config
import { auth } from "../config/firebase";
import { useAuth } from "../auth";

// Components
import Loading from "../components/Loading";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";

export default function Home() {
  const { currentUser } = useAuth();
  const [open, setOpen] = useState(false);
  const [alertType, setAlertType] = useState("success");
  const [alertMessage, setAlertMessage] = useState("");
  const showAlert = (type, msg) => {
    setAlertType(type);
    setAlertMessage(msg);
    setOpen(true);
  };
  const handleClose = (event, reason) => {
    if (reason === "clickaway") {
      return;
    }
    setOpen(false);
  };

  return (
    <div>
      <Head>
        <title>PolygonHR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>PolygonHR</h1>
      </main>
    </div>
  );
}
