// Next.js and React related
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

// Config
import { auth } from "../config/firebase";
import { useAuth } from "../auth";

// Components
import Loading from "../components/Loading";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";
import RadarChart from "../components/RadarChart";

export default function Home() {
  const { currentUser } = useAuth();
  const [open, setOpen] = useState(false);
  const [alertType, setAlertType] = useState("success");
  const [alertMessage, setAlertMessage] = useState("");
  const showAlert = (type, msg) => {
    setAlertType(type);
    setAlertMessage(msg);
    setOpen(true);
  };
  const handleClose = (event, reason) => {
    if (reason === "clickaway") {
      return;
    }
    setOpen(false);
  };

  return (
    <div>
      <Head>
        <title>PolygonHR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 幅サイズはスクリーンの60％指定だが、後で正しく変更する */}
      <main className="flex w-3/4">
        <div className="flex-none w-72">
          <div className="object-center m-4">
            <Image
              className="inline object-cover rounded-full"
              src="/vercel.svg"
              width={256}
              height={256}
              alt="Profile image"
            />
          </div>
          <div className="grid grid-rows-6 grid-flow-col gap-4 m-4">
            <div>Name / Age :</div>
            <div>Dept. / Rank :</div>
            <div>Supervisor :</div>
            <div>Assessor :</div>
            <div>Assigned PJ :</div>
            <div>Role :</div>
            <div>Hiroshi Nishio / 34</div>
            <div>Product Dev / Senior Manager</div>
            <div>James Bond</div>
            <div>Money Penny</div>
            <div>xxx App Development, xxx Marketing KPI</div>
            <div>Developer, Reviewer</div>
          </div>
        </div>
        <RadarChart />
      </main>
    </div>
  );
}
